# Generated by Django 4.2.3 on 2023-07-28 05:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, verbose_name='نام برند')),
                ('brand_nationality', models.CharField(max_length=50, verbose_name='ملیت برند')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True, verbose_name='مدل')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('color', models.CharField(max_length=20, verbose_name='رنگ')),
                ('screen_size', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='اندازه صفحه نمایش')),
                ('is_available', models.BooleanField(default=True, verbose_name='وضعیت موجودی')),
                ('manufacturing_country', models.CharField(max_length=50, verbose_name='کشور سازنده')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه شدن')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='نام در لینک')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_module.brand', verbose_name='برند')),
            ],
            options={
                'verbose_name': 'تلفن همراه',
                'verbose_name_plural': 'تلفن های همراه',
            },
        ),
    ]
